### ISSUE TITLE
Release for GHC 9.0.1

### ISSUE THREAD

**Issue by bgamari** [haskell/hsc2hs#61]
GHC could use a release off of 7accbea001bcac638c4320d3755af29478114901.

**Comment by bgamari** [comment]
Ping.

**Comment by phadej** [comment]
I wonder what version GHC-9.0 is bundling?

**Comment by andreasabel** [comment]
@bgamari : Could you do it yourself, maybe?  You are listed as maintainers of `hsc2hs` at https://hackage.haskell.org/package/hsc2hs/maintainers/.  Or is it more complicated?

**Comment by bgamari** [comment]
It's a bit more complicated; while I am in the maintainer set to push revisions (e.g. to accommodate new GHC releases), I was never granted permission to make proper releases. However, given the state of things, I think I may just have to assert full maintainership to get things unstuck.

**Comment by andreasabel** [comment]
What I hear from Herbert is that he is super busy with his full-time job, family, kids and teaching assignment at TU Vienna and he is hardly available atm.
I would think that fixes that keep the package functioning in an evolving ecosystem are covered by the spirit of your assignment, even if this requires a release rather than a revision.

**Comment by bgamari** [comment]
I have pushed a 0.68.8 release.
